---
- name: Copy host key
  ansible.builtin.copy:
    content: "{{ concourse_host_key }}"
    dest: "{{ concourse_host_key_path }}"
    owner: "{{ concourse_user }}"
    group: "{{ concourse_group }}"
    mode: "{{ concourse_etc_files_mode }}"
  become: true
  notify:
    - Restart concourse web

- name: Copy session signing key
  ansible.builtin.copy:
    content: "{{ concourse_session_signing_key }}"
    dest: "{{ concourse_session_signing_key_path }}"
    owner: "{{ concourse_user }}"
    group: "{{ concourse_group }}"
    mode: "{{ concourse_etc_files_mode }}"
  become: true
  notify:
    - Restart concourse web

- name: Copy authorized worker keys
  ansible.builtin.template:
    src: authorized_worker_keys.j2
    dest: "{{ concourse_authorized_worker_keys_path }}"
    owner: "{{ concourse_user }}"
    group: "{{ concourse_group }}"
    mode: "{{ concourse_etc_files_mode }}"
  become: true
  notify:
    - Restart concourse web

- name: Tls certificate | Concourse
  ansible.builtin.copy:
    content: "{{ concourse_tls_certificate }}"
    dest: "{{ concourse_tls_certificate_path }}"
    owner: "{{ concourse_user }}"
    group: "{{ concourse_group }}"
    mode: "{{ concourse_etc_files_mode }}"
  become: true
  when: concourse_tls_certificate is defined
  notify:
    - Restart concourse web

- name: Tls key | Concourse
  ansible.builtin.copy:
    content: "{{ concourse_tls_key }}"
    dest: "{{ concourse_tls_key_path }}"
    owner: "{{ concourse_user }}"
    group: "{{ concourse_group }}"
    mode: "{{ concourse_etc_files_mode }}"
  become: true
  when: concourse_tls_key is defined
  notify:
    - Restart concourse web

- name: Copy resource type defaults
  ansible.builtin.copy:
    content: "{{ concourse_base_resource_type_defaults | to_nice_yaml }}"
    dest: "{{ concourse_base_resource_type_defaults_file }}"
    owner: "{{ concourse_user }}"
    group: "{{ concourse_group }}"
    mode: "{{ concourse_etc_files_mode }}"
  become: true
  when: concourse_base_resource_type_defaults is defined
  notify:
    - Restart concourse web
