---
- name: Probe btrfs module
  modprobe:
    name: btrfs
    state: present
  become: true
  when: concourse_baggageclaim_driver == 'btrfs'

- name: Install btrfs-progs package
  ansible.builtin.package:
    name: btrfs-progs
    state: present
  become: true
  when: concourse_baggageclaim_driver == 'btrfs'

- name: Probe overlay module
  modprobe:
    name: overlay
    state: present
  become: true
  when: concourse_baggageclaim_driver == 'overlay'

- name: Unmount work volume
  mount:
    path: "{{ concourse_work_volume_mount_path }}"
    state: unmounted
  become: true
  ignore_errors: true
  register: unmount_work_volume

- name: Create work volume filesystem
  filesystem:
    dev: "{{ concourse_work_volume_device }}"
    fstype: "{{ concourse_work_volume_fs_type }}"
    force: "{{ concourse_work_volume_fs_force_create }}"
    resizefs: "{{ concourse_work_volume_fs_resize }}"
  become: true
  when: unmount_work_volume is succeeded

- name: Mount work volume
  mount:
    path: "{{ concourse_work_volume_mount_path }}"
    src: "{{ concourse_work_volume_device }}"
    fstype: "{{ concourse_work_volume_fs_type }}"
    opts: "{{ concourse_work_volume_mount_opts }}"
    state: mounted
  become: true
  when: unmount_work_volume is succeeded
