---
- name: Create work directory
  ansible.builtin.file:
    path: "{{ concourse_work_dir }}"
    state: directory
    mode: "0750"
    owner: "{{ concourse_user }}"
    group: "{{ concourse_group }}"
  become: true

- name: Setup filesystem
  ansible.builtin.import_tasks: filesystem.yml
  when: concourse_manage_work_volume

- name: Create worker launch script
  ansible.builtin.template:
    src: concourse-worker.j2
    dest: "{{ concourse_worker_launcher_path }}"
    owner: "{{ concourse_user }}"
    group: "{{ concourse_group }}"
    mode: "{{ concourse_worker_binary_mode }}"
    force: true
  become: true
  notify:
    - restart concourse worker

- name: Create worker land script
  ansible.builtin.template:
    src: concourse-land-worker.j2
    dest: "{{ concourse_worker_land_path }}"
    owner: "{{ concourse_user }}"
    group: "{{ concourse_group }}"
    mode: "{{ concourse_worker_binary_mode }}"
    force: true
  become: true

- name: Create worker retire script
  ansible.builtin.template:
    src: concourse-retire-worker.j2
    dest: "{{ concourse_worker_retire_path }}"
    owner: "{{ concourse_user }}"
    group: "{{ concourse_group }}"
    mode: "{{ concourse_worker_binary_mode }}"
    force: true
  become: true

- name: Create worker service
  ansible.builtin.template:
    src: concourse-worker.service.j2
    dest: /etc/systemd/system/concourse-worker.service
    owner: root
    mode: "0644"
    force: true
  become: true
  register: concourse_worker_service
  notify:
    - restart concourse worker
    - systemd daemon reload
  tags:
    - no-test
