---
- name: Configure web
  ansible.builtin.import_tasks: web/configure.yml
  when: concourse_web

- name: Configure worker
  ansible.builtin.import_tasks: worker/configure.yml
  when: concourse_worker
