---
- name: Map system architecture to Concourse archive arch
  set_fact:
    concourse_archive_arch: >-
      {{
        {
          'x86_64': 'amd64',
          'aarch64': 'arm64'
        }[ansible_architecture]
      }}
  when: ansible_architecture in ['x86_64', 'aarch64']

- name: Set dynamic checksum for Concourse archive
  set_fact:
    concourse_archive_checksum: >-
      {{
        {
          'arm64': concourse_archive_checksum_arm64,
          'amd64': concourse_archive_checksum_amd64
        }[concourse_archive_arch]
      }}
  when: concourse_archive_arch in ['arm64', 'amd64']

- name: Fail if unsupported architecture
  fail:
    msg: "Unsupported architecture: {{ ansible_architecture }}. Only amd64 and arm64 are supported."
  when: ansible_architecture not in ['x86_64', 'aarch64']

- stat:
    path: "{{ concourse_binary_path }}"
  become: yes
  become_user: root
  ignore_errors: yes
  register: binary

- name: get concourse version
  command: "{{ concourse_binary_path }} -v"
  become: yes
  register: installed_version
  changed_when: false
  when: binary.stat is defined and binary.stat.exists

- name: check needs install
  set_fact:
    needs_install: "{{ not binary.stat.exists or installed_version is defined and installed_version.stdout != concourse_version }}"

- name: download archive
  get_url:
    url: "{{ concourse_archive_url }}"
    dest: "{{ concourse_install_prefix_dir }}/{{ concourse_archive_name }}"
    checksum: "{{ concourse_archive_checksum }}"
    mode: 0755
    force: no
    timeout: "{{ concourse_archive_fetch_timeout }}"
  become: yes
  when: needs_install
  register: binary_download
  tags:
  - no-test

- import_tasks: stop.yml
  when: needs_install

- name: unpack archive
  unarchive:
    src: "{{ concourse_install_prefix_dir }}/{{ concourse_archive_name }}"
    dest: "{{ concourse_install_prefix_dir }}"
    remote_src: yes
    mode: 0755
    owner: "{{ concourse_user }}"
    group: "{{ concourse_group }}"
  become: yes
  when: binary_download is not defined or binary_download is changed
  notify:
  - restart concourse web
  - restart concourse worker

- name: delete archive
  file:
    path: "{{ concourse_install_prefix_dir }}/{{ concourse_archive_name }}"
    state: absent
  become: yes
  when: concourse_archive_delete_after_unarchive

- name: binary permissions
  file:
    path: "{{ concourse_binary_path }}"
    owner: "{{ concourse_user }}"
    group: "{{ concourse_group }}"
    mode: "{{ concourse_binary_mode }}"
  become: yes

- name: create etc dir
  file:
    path: "{{ concourse_etc_dir }}"
    state: directory
    owner: "{{ concourse_user }}"
    group: "{{ concourse_group }}"
    mode: 0750
  become: yes

- name: install postgresql
  import_tasks: postgresql/install.yml
  when: concourse_postgres_install

- name: install web
  import_tasks: web/install.yml
  when: concourse_web

- name: install worker
  import_tasks: worker/install.yml
  when: concourse_worker
