---
- name: create cli-artifacts directory | concourse
  file:
    path: "{{ concourse_cli_artifacts_dir }}"
    state: directory
    mode: 0755
    owner: "{{ concourse_user }}"
    group: "{{ concourse_group }}"
  become: yes
  become_user: root

- name: create web launch script | concourse
  template:
    src: concourse-web.j2
    dest: "{{ concourse_web_launcher_path }}"
    owner: "{{ concourse_user }}"
    group: "{{ concourse_group }}"
    mode: "{{ concourse_web_launcher_mode }}"
    force: yes
  become: yes
  become_user: root
  notify:
  - restart concourse web

- name: create web service | concourse
  template:
    src: concourse-web.service.j2
    dest: /etc/systemd/system/concourse-web.service
    owner: root
    force: yes
  become: yes
  become_user: root
  notify:
  - restart concourse web
