---
- stat:
    path: "{{ concourse_binary_path }}"
  become: yes
  become_user: root
  ignore_errors: yes
  register: binary

- name: get binary version | concourse
  command: "{{ concourse_binary_path }} -v"
  become: yes
  register: installed_version
  changed_when: false
  when: binary.stat is defined and binary.stat.exists

- name: check needs install | concourse
  set_fact:
    needs_install: "{{ not binary.stat.exists or installed_version is defined and installed_version.stdout != concourse_version }}"

- name: create install directory | concourse
  file:
    path: "{{ concourse_install_dir }}"
    state: directory
    mode: 0755
    owner: "{{ concourse_user }}"
    group: "{{ concourse_group }}"
  become: yes

- include: stop.yml
  when: needs_install

- name: download binary | concourse
  get_url:
    url: "{{ concourse_download_url }}"
    dest: "{{ concourse_binary_path }}"
    owner: "{{ concourse_user }}"
    group: "{{ concourse_group }}"
    mode: "{{ concourse_binary_mode }}"
    force: yes
    timeout: "{{ concourse_binary_fetch_timeout }}"
  become: yes
  when: needs_install
  register: binary_download
  notify:
  - restart concourse web
  - restart concourse worker

- name: binary permissions | concourse
  file:
    path: "{{ concourse_binary_path }}"
    owner: "{{ concourse_user }}"
    group: "{{ concourse_group }}"
    mode: "{{ concourse_binary_mode }}"
  become: yes

- name: install web | concourse
  include: install-web.yml
  when: concourse_web

- name: install worker | concourse
  include: install-worker.yml
  when: concourse_worker
