- name: start web | concourse
  service:
    name: concourse-web
    state: started
    enabled: yes
  become: yes
  when: concourse_web

- name: start worker | concourse
  service:
    name: concourse-worker
    state: started
    enabled: yes
  become: yes
  when: concourse_worker
