---
- name: Configure web service
  ansible.builtin.service:
    name: concourse-web
    enabled: "{{ concourse_service_enabled }}"
  become: true
  when: concourse_web
  tags:
    - no-test

- name: Configure worker service
  ansible.builtin.service:
    name: concourse-worker
    enabled: "{{ concourse_service_enabled }}"
  become: true
  when: concourse_worker
  tags:
    - no-test

- name: Start web service
  ansible.builtin.service:
    name: concourse-web
    state: started
  become: true
  when: concourse_web and concourse_service_enabled and concourse_service_start
  tags:
    - no-test

- name: Start worker service
  ansible.builtin.service:
    name: concourse-worker
    state: started
  become: true
  when: concourse_worker and concourse_service_enabled and concourse_service_start
  tags:
    - no-test
