---
- name: Stop web
  ansible.builtin.service:
    name: concourse-web
    state: stopped
  become: true
  ignore_errors: true
  when: concourse_web
  tags:
    - no-test

- name: Stop worker
  ansible.builtin.service:
    name: concourse-worker
    state: stopped
  become: true
  ignore_errors: true
  when: concourse_worker
  tags:
    - no-test
