- name: stop web | concourse
  service:
    name: concourse-web
    state: stopped
  become: yes
  ignore_errors: yes
  when: concourse_web

- name: stop worker | concourse
  service:
    name: concourse-worker
    state: stopped
  become: yes
  ignore_errors: yes
  when: concourse_worker
