- name: stop web | concourse
  service:
    name: concourse-web
    state: stopped
    enabled: yes
  become: yes
  become_user: root
  when: concourse_web

- name: stop worker | concourse
  service:
    name: concourse-worker
    state: stopped
    enabled: yes
  become: yes
  become_user: root
  when: concourse_worker
