---
- name: concourse group
  become: yes
  group:
    name: "{{ concourse_group }}"
    gid: "{{ concourse_gid }}"
  when: concourse_manage_user

- name: concourse user
  become: yes
  user:
    name: "{{ concourse_user }}"
    comment: Concourse CI
    uid: "{{ concourse_uid }}"
    group: "{{ concourse_group }}"
    shell: "/bin/false"
    createhome: no
  when: concourse_manage_user
